### PR TITLE
modified for phone screen

### PR DESCRIPTION
**Pull request by ananyaa07**
Issue: 136

### CODE REVIEW

**Comment by Mudit018** [comment]
@ananyaa07 Provide live link

**Comment by Mudit018** [comment]
@ananyaa07 
image
This section is still not modified, if only this section is modified, then the bugs will be rectified.

**Comment by Mudit018** [comment]
@ananyaa07 pull the changes before making a PR

**Comment by Mudit018** [comment]
@ananyaa07 Resolve conflicts and have all the issues been cleared?

**Comment by ananyaa07** [comment]
@Mudit018 yes sir

**Pull request merged**
