### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by terminatorXbgmi**
Issue: 3

##Short description of what this resolves:
Here I am adding me as a participant by json file.

##Changes proposed in this pull request and/or Screenshots of changes:
-Add me as a participants

### CODE REVIEW

**Comment by Manas2403** [comment]
@terminatorXbgmi  PR template is not followed

**Comment by atharva-gadekar** [comment]
@terminatorXbgmi Resolve conflicts! Try not to make multiple commits.

**Review by atharva-gadekar — CHANGES_REQUESTED** [review]
@terminatorXbgmi Resolve conflicts! Try not to make multiple commits.

**Review by Manas2403 — CHANGES_REQUESTED** [review]
If there is no facebook you have to leave that field empty string. @terminatorXbgmi

**Pull request closed without merging**
