### PR TITLE
Update Participants.json

### PR DESCRIPTION
**Pull request by Kali-Decoder**
Issue: 3

#### Short description of what this resolves:
Add My self in Participants List.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by Manas2403 — CHANGES_REQUESTED** [review]
@Kali-Decoder  you have created two pull requests for the same issue.

**Comment by Kali-Decoder** [comment]
@Manas2403  can you accept one other one i delete

**Comment by Manas2403** [comment]
First delete the PR you don't want and  resolve conflicts.

**Comment by Kali-Decoder** [comment]
One pr is for issue 3 and other pr is for issue 47 . And Conflict is resolved can you see @Manas2403

**Comment by Kali-Decoder** [comment]
@Manas2403  Done Sir

**Pull request closed without merging**
