### PR TITLE
added herosection

### PR DESCRIPTION
**Pull request by GammaMicrowave**
Issue: 77
#### Short description of what this resolves:
added hero seection in index.html

#### Changes proposed in this pull request and or Screenshots of changes:
-added a new hero.js file to provide js for html doc
-initialized node to install a library called animejs
-used anime js to create a staggered effect
-merged hero section and footer in a single file and fixed the issues occuring in footer 
-the hero section is also responsive.

here  are some images of the  staggering effect 

Screenshot 2022-12-27 022509

Screenshot 2022-12-27 022514

### CODE REVIEW

**Comment by Mudit018** [comment]
@GammaMicrowave Provide a live link to website

**Comment by GammaMicrowave** [comment]
Sir I have sent the html file in discord channel you can check it

**Comment by Mudit018** [comment]
> Sir I have sent the html file in discord channel you can check it

Kindly provide the link as it was conveyed earlier that you have to provide a live link for every PR

**Comment by Mudit018** [comment]
And kindly pull the changes before pushing your code.

**Pull request merged**
