### PR TITLE
RESUME

### PR DESCRIPTION
**Pull request by hackerishan-123**
Issue: 47

added resume

### CODE REVIEW

**Comment by hackerishan-123** [comment]
conflict resolved

**Comment by Mudit018** [comment]
These 2 are different issues, you had to make 2 PRs

**Comment by hackerishan-123** [comment]
yes, i have made different pr for both issues, but i don't know how it is coming here ...

**Comment by hackerishan-123** [comment]
only merge  'add resume' one..

**Comment by Manas2403** [comment]
You have deleted participants.json. I would suggest create a fresh PR if you are not able to resolve conflicts.

**Pull request closed without merging**
