### PR TITLE
added move to top button (issue 76)

### PR DESCRIPTION
**Pull request by iamatifmoin**
Issue: #76

#### Short description of what this resolves:

I have added the move-to-top button

#### This is what it looks like on the bottom-right:
OpenCode

### CODE REVIEW

**Comment by Mudit018** [comment]
Provide live link to website

**Comment by iamatifmoin** [comment]
https://iamatifmoin.github.io/Collaborative-Web-2022/

You wont be able to view the button till you scroll on the page.

**Comment by Mudit018** [comment]
Then wait for one PR to get merged and then I'll check yours

**Comment by iamatifmoin** [comment]
I'll have to resolve conflicts then.

Should i just link a video to showcase?

**Pull request closed without merging**
