### PR TITLE
Added my details

### PR DESCRIPTION
**Pull request by JahnaviGadde**
Issue: 3

#### Short description of what this resolves:
Added my details

#### Changes proposed in this pull request and/or Screenshots of changes:
Added my details
-
-
-

### CODE REVIEW

**Comment by Mudit018** [comment]
The issue number is wrong, kindly correct it.

**Comment by JahnaviGadde** [comment]
done

**Comment by Manas2403** [comment]
@JahnaviGadde  you have created multiple PRs for the same task.  Close the PR which is not required

**Comment by JahnaviGadde** [comment]
done

**Pull request closed without merging**
