### PR TITLE
Adding Siddhant Agarwal in students section

### PR DESCRIPTION
**Pull request by Siddhant-Agarwal4583**
Issue: 3

#### Short description of what this resolves:
Added me as a participant in participants.json

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by homewardgamer** [comment]
resolve merge conflicts

**Comment by Siddhant-Agarwal4583** [comment]
Solve kar dia

**Comment by homewardgamer** [comment]
@Siddhant-Agarwal4583 , wrong format of file, fix JSON object.

**Comment by Siddhant-Agarwal4583** [comment]
Isme galti kaha hai?

**Comment by Siddhant-Agarwal4583** [comment]
Isme galti kaha hai?

**Pull request merged**
