### PR TITLE
added scroll to top button

### PR DESCRIPTION
**Pull request by iamatifmoin**
Issue: 76 

#### Short description of what this resolves:

Added scroll to top button. @Mudit018 

#### Changes proposed in this pull request and/or Screenshots of changes:

- 
OpenCode (1)

-
-

### CODE REVIEW

**Comment by Mudit018** [comment]
PR template not followed and provide a link to website

**Comment by iamatifmoin** [comment]
> PR template not followed and provide a link to website

https://iamatifmoin.github.io/Collaborative-Web-2022/

**Comment by Mudit018** [comment]
Your PR template is wrong
kindly correct it
remove #

**Comment by iamatifmoin** [comment]
> Your PR template is wrong kindly correct it remove #

Done

**Pull request merged**
