### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by Aman1143**
Issue: 41

### CODE REVIEW

**Comment by Mudit018** [comment]
@Aman1143 
Please provide a live link to website

**Comment by Aman1143** [comment]
https://aman1143.github.io/Collaborative-Web-2022/
this is live link

**Comment by Mudit018** [comment]
> https://aman1143.github.io/Collaborative-Web-2022/ this is live link

Remove the white background of favicon

**Comment by Mudit018** [comment]
> https://aman1143.github.io/Collaborative-Web-2022/ this is live link

Also provide the image in the description of PR

**Comment by Aman1143** [comment]
fav

This is screenshot of favicon.

**Review by Manas2403 — CHANGES_REQUESTED** [review]
You have still not removed the white background @Aman1143

**Comment by Aman1143** [comment]
fav1
 Is this ok ??

**Comment by Aman1143** [comment]
fav2

Is this better ??

**Comment by Aman1143** [comment]
fav

**Pull request closed without merging**
