### PR TITLE
added timer

### PR DESCRIPTION
**Pull request by harshitgautam2003**
Issue: 89

#### Short description of what this resolves:

Added the countdown timer

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Mudit018** [comment]
@harshitgautam2003 
resolve conflicts once and provide a link after pulling and merging conflicts

**Comment by harshitgautam2003** [comment]
conflicts resolved and merged

**Comment by Mudit018** [comment]
Provide a live link

**Comment by Mudit018** [comment]
Resolve conflicts once more

**Pull request closed without merging**
