### PR TITLE
Create: Navbar

### PR DESCRIPTION
**Pull request by Kali-Decoder**
Issue: 145

#### Short description of what this resolves:

create New Navbar 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Mudit018** [comment]
@Kali-Decoder provide a live link

**Review by Manas2403 — CHANGES_REQUESTED** [review]
@Kali-Decoder  provide live-link else i need to reassign the task

**Comment by Kali-Decoder** [comment]
link : http://127.0.0.1:5500/index.html

**Comment by Manas2403** [comment]
Host it on GitHub pages, this link won't work bcoz it works on your local only

**Comment by Kali-Decoder** [comment]
Okk

**Comment by Kali-Decoder** [comment]
https://kali-decoder.github.io/Collaborative-Web-2022/

**Comment by Manas2403** [comment]
The navbar does not go with the theme change the styling @Kali-Decoder

**Pull request closed without merging**
